/**
 * Registry-Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AspNetUserToken } from './aspNetUserToken';
import { SoftwareHistory } from './softwareHistory';
import { AspNetUserLogin } from './aspNetUserLogin';
import { AspNetRole } from './aspNetRole';
import { Device } from './device';
import { Software } from './software';
import { DeviceHistory } from './deviceHistory';
import { AspNetUserClaim } from './aspNetUserClaim';


export interface AspNetUser { 
    id?: string | null;
    userName?: string | null;
    normalizedUserName?: string | null;
    email?: string | null;
    normalizedEmail?: string | null;
    emailConfirmed?: boolean;
    passwordHash?: string | null;
    securityStamp?: string | null;
    concurrencyStamp?: string | null;
    phoneNumber?: string | null;
    phoneNumberConfirmed?: boolean;
    twoFactorEnabled?: boolean;
    lockoutEnd?: string | null;
    lockoutEnabled?: boolean;
    accessFailedCount?: number;
    readonly aspNetUserClaims?: Array<AspNetUserClaim> | null;
    readonly aspNetUserLogins?: Array<AspNetUserLogin> | null;
    readonly aspNetUserTokens?: Array<AspNetUserToken> | null;
    readonly deviceHistories?: Array<DeviceHistory> | null;
    readonly devices?: Array<Device> | null;
    readonly softwareHistories?: Array<SoftwareHistory> | null;
    readonly softwares?: Array<Software> | null;
    readonly roles?: Array<AspNetRole> | null;
}

