/**
 * Registry-Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AspNetUser } from './aspNetUser';


export interface AspNetUserClaim { 
    id?: number;
    userId?: string | null;
    claimType?: string | null;
    claimValue?: string | null;
    user?: AspNetUser;
}

