/**
 * Registry-Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AspNetRole } from './aspNetRole';


export interface AspNetRoleClaim { 
    id?: number;
    roleId?: string | null;
    claimType?: string | null;
    claimValue?: string | null;
    role?: AspNetRole;
}

