/**
 * Registry-Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AspNetRoleClaim } from './aspNetRoleClaim';
import { AspNetUser } from './aspNetUser';


export interface AspNetRole { 
    id?: string | null;
    name?: string | null;
    normalizedName?: string | null;
    concurrencyStamp?: string | null;
    readonly aspNetRoleClaims?: Array<AspNetRoleClaim> | null;
    readonly users?: Array<AspNetUser> | null;
}

