/**
 * Registry-Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AspNetUser } from './aspNetUser';


export interface AspNetUserToken { 
    userId?: string | null;
    loginProvider?: string | null;
    name?: string | null;
    value?: string | null;
    user?: AspNetUser;
}

