/**
 * Registry-Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SoftwaresForUserResponse { 
    userName?: string | null;
    softwareName?: string | null;
    startDate?: string;
}

