/**
 * Registry-Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Software } from './software';
import { AspNetUser } from './aspNetUser';


export interface SoftwareHistory { 
    id?: number;
    userId?: string | null;
    softwareId?: number;
    startDate?: string;
    endDate?: string | null;
    software?: Software;
    user?: AspNetUser;
}

